apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  mycompany.com/policy-version: "1.1.0"

resources:
  - require-department-label/policy.yaml
  - require-known-department-label/policy.yaml