name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:

  kyverno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Get kyverno
        run: wget -q -O - https://github.com/kyverno/kyverno/releases/download/v1.5.4/kyverno-cli_v1.5.4_linux_x86_64.tar.gz | tar -C /usr/local/bin -xzf - kyverno

      - name: Kyverno tests
        run: kyverno test kubernetes/kyverno

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Get checkov
        run: pip install checkov

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.6.0

      - name: BATS tests
        continue-on-error: true
        run: bats --report-formatter junit infra/checkov/test.bats

      - name: Test Report
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 # renovate: tag=v1.5.0
        if: always()
        with:
          name: checkov results
          path: report.xml
          reporter: java-junit
          fail-on-error: false

  # release:
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   runs-on: ubuntu-latest
  #   needs:
  #     - kyverno
  #     - semver

  #   permissions:
  #     contents: write
  #     id-token: write

  #   steps:
  #     - uses: actions/checkout@v2.4.0
  #     - uses: "marvinpinto/action-automatic-releases@v1.2.1"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         automatic_release_tag: ${{ needs.semver.outputs.semantic_version}}
  #         prerelease: false
  #         title: ${{ needs.semver.outputs.semantic_version}}
  #         files: "*"


  semver:
    name: Generate a semantic version number
    runs-on: ubuntu-latest
    outputs:
      semantic_version: ${{ steps.semver.outputs.semantic_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Semver run
        id: semver
        uses: lukaszraczylo/semver-generator@1.12.113
        with:
          config_file: .github/semver.yaml
          repository_local: true